# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-31 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecretModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('public_key', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserSecret',
                'verbose_name_plural': 'UserSecrets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersecretmodel',
            unique_together=set([('user', 'secret_key', 'public_key')]),
        ),
    ]
